//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Drink
    {
        public Drink()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public System.Guid DrinkID { get; set; }
        public string DrinkName { get; set; }
        public string Notes { get; set; }
    
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}
