//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Food
    {
        public Food()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public System.Guid FoodID { get; set; }
        public string FoodName { get; set; }
        public string Notes { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> DiscountPrice { get; set; }
        public Nullable<System.Guid> MenuTypeID { get; set; }
        public string imagePath { get; set; }
    
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}
