//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantManagementSystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OasisRestaurantEntities : DbContext
    {
        public OasisRestaurantEntities()
            : base("name=OasisRestaurantEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<DeliveryDriverInfo> DeliveryDriverInfoes { get; set; }
        public virtual DbSet<Drink> Drinks { get; set; }
        public virtual DbSet<Feed> Feeds { get; set; }
        public virtual DbSet<Food> Foods { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<MenuType> MenuTypes { get; set; }
        public virtual DbSet<OrderDelivery> OrderDeliveries { get; set; }
        public virtual DbSet<OrderDetail> OrderDetails { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<OrderStatu> OrderStatus { get; set; }
        public virtual DbSet<Store> Stores { get; set; }
        public virtual DbSet<UserAdmin> UserAdmins { get; set; }
    }
}
